spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=myappdb;encrypt=false;trustServerCertificate=true
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    username: myuser
    password: mypassword

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.SQLServer2012Dialect
    show-sql: false
