spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=master;encrypt=false
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    username: myuser
    password: mypassword
  
  jpa:
    database-platform: org.hibernate.dialect.SQLServer2012Dialect
    hibernate:
      ddl-auto: validate
    show-sql: false